# Generated by Django 3.1.4 on 2020-12-29 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartmodel',
            name='food_id',
        ),
        migrations.AddField(
            model_name='cartmodel',
            name='food_name',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='cartmodel',
            name='food_price',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
